name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    environment: Terraform  # Especifica el entorno aquí

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print AWS Access Key for Debugging
        run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Print Environment Variables
        run: env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.6'

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan -var-file=env.tfvars -out=tfplan
        working-directory: ./

      - name: Terraform Apply
        run: terraform apply -var-file=env.tfvars -auto-approve tfplan
        working-directory: ./

      - name: Terraform Output
        run: terraform output
        working-directory: ./